config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
    resources :impersonates do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
    end
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_blog.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Blog Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/blog/">



    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      div.vertical-panel {
        writing-mode: vertical-rl;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">
  </head>
  <body>

<div class="container">


  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <a class="p-2 link-secondary" target='blank' href="https://playful-dry-d40.notion.site/Home-e2214901e7274778b5545eebde54a9d6">🧑‍🏫 Notion Course Website</a>
      <a class="p-2 link-secondary" target='blank' href="https://open.spotify.com/playlist/2u6BFi7YKZ2WCppbHEZnYf?si=b667bcc4a92f451b">🎵 Music</a>
      <a class="p-2 link-secondary" target='blank' href="https://www.wikiwand.com/en/Lu_Xun">📚 Books</a>
      <a class="p-2 link-secondary" target='blank' href="https://translate.google.com/?sl=en&tl=zh-CN&op=translate">🧘 Google Translate</a>
      <a class="p-2 link-secondary" target='blank' href="https://ctext.org/wiki.pl?if=en&chapter=754186">📝 Zen Poems</a>
      <a class="p-2 link-secondary" target='blank' href="https://open.spotify.com/show/04re9FvL1xviHGWvXKoAhZ?si=4ea392b4c24f42f5">🗣 Podcasts</a>
      <a class="p-2 link-secondary" target='blank' href="https://www.youtube.com/watch?v=_IWtVDr6DCk">🀄️ Speeches</a>
      <a class="p-2 link-secondary" target='blank' href="https://www.okcu.edu/academics/global/studyabroad">🌏 Study Abroad</a>
      <a class="p-2 link-secondary" target='blank' href="https://www.fellowships4you.com/">💰 Fellowships</a>
      <a class="p-2 link-secondary" target='blank' href="https://www.middlebury.edu/language-schools/languages/chinese">🥳 Middlebury Language Schools</a>
      <a class="p-2 link-secondary" target='blank' href="https://www.wikiwand.com/en/Chinese_science_fiction">🥽 Science Fiction</a>
    </nav>
  </div>
</div>

<main class="container">
  <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <div class="vertical-panel">
      <h1 class="display-4 fst-italic">好久不見</h1>
      <p class="lead my-3">
      那個冬天我先去了香港而後回到我家俄克拉荷馬。當時以為只會過兩個星期而回北京。其實不然。

在路上我走著，想念在北京的朋友們—北京所能吃的，能學得，能看得，等等。突然看到了一位中國阿姨。‘不可能的‘，我想。她走向我們小區的小山。天氣那個時候不冷不熱，太陽日落。’這位可能是我說中文的答案，經歷北京在這裡的這一個機會‘，“艾！好久不見！”

齁阿姨停著，回頭看我的。我大大地笑而走過去了。“我認識你嗎？“ 齁阿姨問到。

”我們極有可能是上一輩子認識的。“

齁阿姨笑了，告訴我她性齁也不是猴子的猴。她也是剛來的，也因為病情不能回去的。我們都笑了二繼續走。

我們一起走著到他家去。而後認識了她女兒和她女兒的女兒。他們跟我說每天晚上有個中國阿姨協會組合在湖邊。邀請我去。所以我去了。
      </p>
      </div>
    </div>
  </div>

  <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <div class="vertical-panel">
      <h1 class="display-4 fst-italic">三人行</h1>
      <p class="lead my-3">
   我們快到三年是天天晚上看看報紙喝喝茶打著麻將。有的阿姨們抽菸，所有的經過了文化大革命，改革開放，貿易戰，和觀眾病毒。

老潘和曹阿姨差不多是我的父母了。曹阿姨給我包餃子發起短信，我平常不會打。

現在有一位王老師教了我很多。
      </p>
      </div>
    </div>
  </div>


 <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <div class="vertical-panel">
      <h1 class="display-4 fst-italic">王老師</h1>
      <p class="lead my-3">
   王老師終於告訴了我為什麼他討厭現狀在大陸—就是因為在他小農村文革時有人批鬥而殺他爺爺。爺爺去世之後，他奶奶，父母和他都被批鬥了。
      </p>
      </div>
    </div>
  </div>

   <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <div class="vertical-panel">
      <h1 class="display-4 fst-italic">無有十畝田</h1>
      <p class="lead my-3">
        無有十畝田。中在南山破。<br>
        輕鬆四五術。綠豆兩三顆。<br>
        熱即池中浴。兩邊岸上歌。<br>
        遨遊自取組。誰能奈我何？
      </p>
      </div>
    </div>
  </div>


  <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <div class="vertical-panel">
      <h1 class="display-4 fst-italic">吾是張武心</h1>
      <p class="lead my-3">
        無是張武心。漢三的兄弟。<br>
        文婷的朋友。給六成寫信。<br>
        王米慧聰明。黃河有能力。<br>
        叫琳慧夢熙。玩電腦遊戲？
      </p>
      </div>
    </div>
  </div>



  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary"></strong>
          <h3 class="mb-0">1. 🧑‍🏫 木老师 Mù lǎoshī，<br> 2. 📚 吳文婷 Wúwéntíng, <br>3. ☘️ 张汉三 Zhānghànsān, <br>5. 🥷 张武心 Zhāngwǔxīn,<br> 6. 6️⃣ 林六成 Lín liù chéng,<br> 7. 🍚 王米慧 Wángmǐhuì, <br>8. 🌊 司马黄河 Sīmǎ huánghé, <br>9.💎 刘琳慧 Liúlínhuì, <br>10. 💭 李梦熙 Lǐmèngxī   </h3>
          <div class="mb-1 text-muted">玩名字 </div>
        </div>
        <div class="col-auto d-none d-lg-block">

        </div>
      </div>
    </div>


        <div class="p-4">
          <h4 class="fst-italic">Resources</h4>
          <ol class="list-unstyled mb-0">
            <li><a target='blank' href="https://playful-dry-d40.notion.site/Home-e2214901e7274778b5545eebde54a9d6"></a>🧑‍🏫 Notion Course Website</li>
            <li><a target='blank' href="https://open.spotify.com/playlist/2u6BFi7YKZ2WCppbHEZnYf?si=b667bcc4a92f451b">🎵 Music</a></li>
            <li><a target='blank' href="https://www.wikiwand.com/en/Lu_Xun">📚 Books</a></li>
            <li><a target='blank' href="https://translate.google.com/?sl=en&tl=zh-CN&op=translate">🧘 Google Translate</a></li>
            <li><a target='blank' href="https://ctext.org/wiki.pl?if=en&chapter=754186">📝 Zen Poems</a></li>
            <li><a target='blank' href="https://open.spotify.com/show/04re9FvL1xviHGWvXKoAhZ?si=4ea392b4c24f42f5">🗣 Podcasts</a></li>
            <li><a target='blank' href="https://www.youtube.com/watch?v=_IWtVDr6DCk">🀄️ Speeches</a></li>
            <li><a target='blank' href="https://www.okcu.edu/academics/global/studyabroad">🌏 Study Abroad</a></li>
            <li><a target='blank' href="https://www.fellowships4you.com/">💰 Fellowships</a></li>
            <li><a target='blank' href="https://www.middlebury.edu/language-schools/languages/chinesehttps://www.middlebury.edu/language-schools/languages/chinese">🥳 Middlebury Language Schools</a></li>
            <li><a target='blank' href="https://www.wikiwand.com/en/Chinese_science_fictionhttps://www.wikiwand.com/en/Chinese_science_fiction">🥽 Science Fiction</a></li>
          </ol>
        </div>

        <div class="p-4">
          <h4 class="fst-italic">Other Places</h4>
          <ol class="list-unstyled">
            <li><a href="https://github.com/carsonmulligan/zhongwen">👨‍💻 GitHub</a></li>
            <li><a href="https://playful-dry-d40.notion.site/Home-e2214901e7274778b5545eebde54a9d6">🧑‍🏫 Notion Website</a></li>
          </ol>
        </div>
      </div>
    </div>
  </div>

</main>

<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>



  </body>
</html>

app/views/shared/_dashboard.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Dashboard Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">



    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
  </head>
  <body>



<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Orders
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>

      <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

      <h2>Section title</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>random</td>
              <td>data</td>
              <td>placeholder</td>
              <td>text</td>
            </tr>
            <tr>
              <td>1,002</td>
              <td>placeholder</td>
              <td>irrelevant</td>
              <td>visual</td>
              <td>layout</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>data</td>
              <td>rich</td>
              <td>dashboard</td>
              <td>tabular</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>information</td>
              <td>placeholder</td>
              <td>illustrative</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,004</td>
              <td>text</td>
              <td>random</td>
              <td>layout</td>
              <td>dashboard</td>
            </tr>
            <tr>
              <td>1,005</td>
              <td>dashboard</td>
              <td>irrelevant</td>
              <td>text</td>
              <td>placeholder</td>
            </tr>
            <tr>
              <td>1,006</td>
              <td>dashboard</td>
              <td>illustrative</td>
              <td>rich</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,007</td>
              <td>placeholder</td>
              <td>tabular</td>
              <td>information</td>
              <td>irrelevant</td>
            </tr>
            <tr>
              <td>1,008</td>
              <td>random</td>
              <td>data</td>
              <td>placeholder</td>
              <td>text</td>
            </tr>
            <tr>
              <td>1,009</td>
              <td>placeholder</td>
              <td>irrelevant</td>
              <td>visual</td>
              <td>layout</td>
            </tr>
            <tr>
              <td>1,010</td>
              <td>data</td>
              <td>rich</td>
              <td>dashboard</td>
              <td>tabular</td>
            </tr>
            <tr>
              <td>1,011</td>
              <td>information</td>
              <td>placeholder</td>
              <td>illustrative</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,012</td>
              <td>text</td>
              <td>placeholder</td>
              <td>layout</td>
              <td>dashboard</td>
            </tr>
            <tr>
              <td>1,013</td>
              <td>dashboard</td>
              <td>irrelevant</td>
              <td>text</td>
              <td>visual</td>
            </tr>
            <tr>
              <td>1,014</td>
              <td>dashboard</td>
              <td>illustrative</td>
              <td>rich</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,015</td>
              <td>random</td>
              <td>tabular</td>
              <td>information</td>
              <td>text</td>
            </tr>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>


    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg-light footer mt-auto py-3">
  <div class="container d-flex justify-content-between mx-auto text-muted">
    <span>&copy; <%= Date.today.year %> 🥁 一年级大雄</span>
    <ul class="d-inline float-end list-inline mb-0">
      <li class="list-inline-item mr-3"><%= link_to "Terms", terms_path %></li>
      <li class="list-inline-item mr-3"><%= link_to "Privacy", privacy_path %></li>
    </ul>
  </div>
</footer>

app/views/shared/_head.html.erb
<title><%= Rails.configuration.application_name %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= favicon_link_tag asset_path('favicon.ico') %>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

app/views/shared/_navbar.html.erb
<% if current_user != true_user %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to stop_impersonating_madmin_impersonates_path, method: :post do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>

<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container mx-auto">
    <%= link_to Rails.configuration.application_name, root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav me-auto mt-2 mt-md-0">
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "What's New", announcements_path, class: "nav-link #{unread_announcements(current_user)}" %></li>
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to notifications_path, class: "nav-link" do %>
              <span><i class="far fa-bell" aria-hidden="true"></i></span>
            <% end %>
          </li>

          <li class="nav-item dropdown">
            <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", bs_toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              <%= image_tag avatar_path(current_user, size: 40), height: 20, width: 20, class: "rounded" %>
            <% end %>
            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-end" aria-labelledby="navbar-dropdown">
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <% if current_user.admin? && respond_to?(:madmin_root_path) %>
                <div class="dropdown-divider"></div>
                <%= link_to "Admin Area", madmin_root_path, class: "dropdown-item" %>
              <% end %>
              <div class="dropdown-divider"></div>
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="container mt-4 mx-auto">
    <div class="alert <%= bootstrap_class_for(msg_type) %> alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>